src/ShopBundle/Entity/Promotion.php
<?php

namespace ShopBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Promotion
 *
 * @ORM\Table(name="promotions")
 * @ORM\Entity(repositoryClass="ShopBundle\Repository\PromotionRepository")
 */
class Promotion
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     * @Assert\NotBlank()
     *
     *
     */

    private $name;


    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_from", type="datetime")
     * @Assert\NotBlank()
     *
     */
    private $dateFrom;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_to", type="datetime")
     */
    private $dateTo;

    /**
     * @var string
     *
     * @ORM\Column(name="discount", type="decimal", precision=10, scale=2)
     * @Assert\NotBlank()
     *
     */
    private $discount;


    /**
     * @var Category
     * @ORM\ManyToOne(targetEntity="ShopBundle\Entity\Category", inversedBy="promotions")
     * @ORM\JoinColumn(name="category_id", referencedColumnName="id" , nullable=true)
     */

    private $category;
    /**
     * @var Product
     * @ORM\ManyToOne(targetEntity="ShopBundle\Entity\Product", inversedBy="promotions")
     * @ORM\JoinColumn(name="product_id", referencedColumnName="id" ,nullable=true)
     */

    private $product;

    /**
     *  @var string
     * @ORM\Column(name="userdefined", type="string", length=255)
     */


    private $userdefined;

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }


    /**
     * @return Category|boolean
     */
    public function getCategory()
    {

            return $this->category;


    }

    /**
     * @param Category $category
     */
    public function setCategory($category)
    {
        $this->category = $category;
    }

    /**
     * @return Product
     */
    public function getProduct()
    {
        return $this->product;
    }

    /**
     * @param Product $product
     */
    public function setProduct($product)
    {
        $this->product = $product;
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set dateFrom
     *
     * @param \DateTime $dateFrom
     *
     * @return Promotion
     */
    public function setDateFrom($dateFrom)
    {
        $this->dateFrom = $dateFrom;

        return $this;
    }

    /**
     * Get dateFrom
     *
     * @return \DateTime
     */
    public function getDateFrom()
    {
        return $this->dateFrom;
    }

    /**
     * Get dateFrom
     *
     * @return string
     */
    public function getDateStart()
    {
        return $this->dateFrom->format('Y-m-d');
    }


    /**
     * Set dateTo
     *
     * @param \DateTime $dateTo
     *
     * @return Promotion
     */
    public function setDateTo($dateTo)
    {
        $this->dateTo = $dateTo;

        return $this;
    }

    /**
     * Get dateTo
     *
     * @return \DateTime
     */
    public function getDateTo()
    {
        return $this->dateTo;
    }

    /**
     * Get dateTo
     *
     * @return string
     */
    public function getDateEnd()
    {
        return $this->dateTo->format('Y-m-d');
    }

    /**
     * Set discount
     *
     * @param string $discount
     *
     * @return Promotion
     */
    public function setDiscount($discount)
    {
        $this->discount = $discount;

        return $this;
    }

    /**
     * Get discount
     *
     * @return string
     */
    public function getDiscount()
    {
        return $this->discount;
    }

    /**
     * @return string
     *
     */

    function __toString()
    {
        $objectName = __Class__;
        $names = explode("\\", $objectName);
        $name = array_pop($names);
        return $name;
    }

    public function getRule()
    {

        $string = 'date(\'now\') >= date(\'' . $this->getDateStart() . '\') and date(\'now\') <= date(\'' . $this->getDateEnd() . '\') ? ' . ($this->discount / 100) . ' : 0';
        return $string;

    }


    //"date('now') >= date('2017-01-20') and date('now') <= date('2018-02-02') ? 0.05 : 0"

    /**
     * @return array
     *
     */

    public function getHeadCategory()
    {

        return ['name', 'dateStart', 'dateEnd', 'discount', ['category' => 'Name']];

    }

    public function getHeadProduct()
    {

        return ['name', 'dateStart', 'dateEnd', 'discount', ['product' => 'Name']];

    }


    public function getHeadUser()
    {

        return ['name', 'dateStart', 'dateEnd', 'discount', 'userdefined'];

    }

    /**
     * @return string
     */
    public function getUserdefined()
    {
        return $this->userdefined;
    }

    /**
     * @param string $userdefined
     */
    public function setUserdefined($userdefined)
    {
        $this->userdefined = $userdefined;
    }

}

src/ShopBundle/Form/PromotionType.php
<?php

namespace ShopBundle\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PromotionType extends AbstractType
{


    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('name',TextType::class)
            ->add('dateFrom',DateType::class)
            ->add('dateTo' ,DateType::class)
            ->add('discount',NumberType::class,["label"=>"Percent"]);
    }


    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'inherit_data' => true
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'shopbundle_promotion';
    }


    /* public function finishView(FormView $view, FormInterface $form, array $options)
     {
         $new_choice = new ChoiceView(array(), '-1', 'All'); // <- new option

         // $view->children["category"]->vars["choices"][1] = $new_choice;//<- adding the new option
         array_unshift($view->children["category"]->vars["choices"],$new_choice);
         array_unshift($view->children["product"]->vars["choices"],$new_choice);

     }*/

}

src/ShopBundle/Controller/PromotionController.php
<?php

namespace ShopBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use ShopBundle\Entity\Promotion;
use ShopBundle\Form\CategoryPromotionType;
use ShopBundle\Form\ProductPromotionType;
use ShopBundle\Form\UserPromotionType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;


/**
 * Class PromotionController
 * @package ShopBundle\Controller
 *
 * @Route("manage/",name="data_manage")
 */
class PromotionController extends Controller
{
    public function indexAction($name)
    {
        return $this->render('', array('name' => $name));
    }

    /**
     *
     * @return \Symfony\Component\HttpFoundation\Response
     *
     * @Route("promotion/list/category", name="promotion_list_c" )
     */

    public function listCategoryPromotionsAction(Request $request)
    {
        $paginator = $this->get('knp_paginator');
        $query = $this->getDoctrine()->getRepository("ShopBundle:Promotion")
            ->findCategoryPromotions();
        $pagination = $paginator->paginate(
            $query->getQuery(),
            $request->query->getInt('page', 1), 6);
        try {
            return $this->render('@Shop/Promotion/categorylist.html.twig', array('pagination' => $pagination));
        } catch (\Exception $e) {


        }

        $this->addFlash('info', "First Create  Promotion");
        return $this->redirectToRoute('promotion_add_c');
    }

    /**
     *
     * @return \Symfony\Component\HttpFoundation\Response
     *
     * @Route("promotion/list/product", name="promotion_list_p" )
     */

    public function listProductPromotionsAction(Request $request)
    {
        $paginator = $this->get('knp_paginator');
        $query = $this->getDoctrine()->getRepository("ShopBundle:Promotion")
            ->findProductPromotions();
        $pagination = $paginator->paginate(
            $query->getQuery(),
            $request->query->getInt('page', 1), 6);
        try {
            return $this->render('@Shop/Promotion/productlist.html.twig', array('pagination' => $pagination));
        } catch (\Exception $e) {


        }

        $this->addFlash('info', "First Create  Promotion");
        return $this->redirectToRoute('promotion_add_p');
    }

    /**
     *
     * @return \Symfony\Component\HttpFoundation\Response
     *
     * @Route("promotion/list/user", name="promotion_list_u" )
     */

    public function listUserPromotionsAction(Request $request)
    {
        $paginator = $this->get('knp_paginator');
        $query = $this->getDoctrine()->getRepository("ShopBundle:Promotion")
            ->findUserPromotion();
        $pagination = $paginator->paginate(
            $query->getQuery(),
            $request->query->getInt('page', 1), 6);
        try {
            return $this->render('@Shop/Promotion/userlist.htm.twig', array('pagination' => $pagination));
        } catch (\Exception $e) {


        }

        $this->addFlash('info', "First Create  Promotion");
        return $this->redirectToRoute('promotion_add_u');
    }

    /**
     * @return \Symfony\Component\HttpFoundation\Response
     *
     * @Route("promotion/create/category", name="promotion_add_c")
     * @Method({"GET"})
     */


    public function createCategoryPromotionsAction()
    {

        $form = $this->createForm(CategoryPromotionType::class);
        $form->add("create", SubmitType::class, array(
            'attr' => array('class' => 'btn-success', 'formnovalidate' => true)))
            ->add("cancel", SubmitType::class, array(
                'attr' => array('class' => 'btn-primary', 'formnovalidate' => true)));

        return $this->render('@Shop/Promotion/create.html.twig',
            ['promotionForm' => $form->createView()]);

    }

    /**
     * @return \Symfony\Component\HttpFoundation\Response
     *
     * @Route("promotion/create/product", name="promotion_add_p")
     * @Method({"GET"})
     */


    public function createProductPromotionsAction()
    {

        $form = $this->createForm(ProductPromotionType::class);
        $form->add("create", SubmitType::class, array(
            'attr' => array('class' => 'btn-success', 'formnovalidate' => true)))
            ->add("cancel", SubmitType::class, array(
                'attr' => array('class' => 'btn-primary', 'formnovalidate' => true)));

        return $this->render('@Shop/Promotion/create.html.twig',
            ['promotionForm' => $form->createView()]);

    }


    /**
     * @return \Symfony\Component\HttpFoundation\Response
     *
     * @Route("promotion/create/user", name="promotion_add_u")
     * @Method({"GET"})
     */


    public function createUserPromotionsAction()
    {

        $form = $this->createForm(UserPromotionType::class);
        $form->add("create", SubmitType::class, array(
            'attr' => array('class' => 'btn-success', 'formnovalidate' => true)))
            ->add("cancel", SubmitType::class, array(
                'attr' => array('class' => 'btn-primary', 'formnovalidate' => true)));

        return $this->render('@Shop/Promotion/usercreate.html.twig',
            ['promotionForm' => $form->createView()]);

    }


    /**
     * @return \Symfony\Component\HttpFoundation\Response
     * @param $id
     * @Route("promotion/create/category", name="promotion_add_process_c")
     * @Method({"POST"})
     */
    public function addPromotionProccessActon(Request $request)

    {
        $Promotion = new Promotion();
        $form = $this->createForm(CategoryPromotionType::class, $Promotion)
            ->add("create", SubmitType::class, array(
                'attr' => array('class' => 'btn-success', 'formnovalidate' => true)))
            ->add("cancel", SubmitType::class, array(
                    'attr' => array('class' => 'btn-primary', 'formnovalidate' => true))
            );
        $form->handleRequest($request);
        if ($form->get('cancel')->isClicked()) {
            return $this->redirectToRoute('promotion_list_c');
        }

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($Promotion);
            $entityManager->flush();

            $this->addFlash("info", "Promotion with name " . $Promotion->getName() . " was added successfully");


            return $this->redirectToRoute('promotion_list_c');


        }


        return $this->render('@Shop/Promotion/create.html.twig',
            ['PromotionForm' => $form->createView()]);


    }

    /**
     * @return \Symfony\Component\HttpFoundation\Response
     * @param $id
     * @Route("promotion/create/product", name="promotion_add_process_p")
     * @Method({"POST"})
     */
    public function addProductPromotionProccessActon(Request $request)

    {
        $Promotion = new Promotion();
        $form = $this->createForm(ProductPromotionType::class, $Promotion)
            ->add("create", SubmitType::class, array(
                'attr' => array('class' => 'btn-success', 'formnovalidate' => true)))
            ->add("cancel", SubmitType::class, array(
                    'attr' => array('class' => 'btn-primary', 'formnovalidate' => true))
            );
        $form->handleRequest($request);
        if ($form->get('cancel')->isClicked()) {
            return $this->redirectToRoute('promotion_list_p');
        }

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($Promotion);
            $entityManager->flush();

            $this->addFlash("info", "Promotion with name " . $Promotion->getName() . " was added successfully");


            return $this->redirectToRoute('promotion_list_p');


        }


        return $this->render('@Shop/Promotion/create.html.twig',
            ['PromotionForm' => $form->createView()]);


    }

    /**
     * @return \Symfony\Component\HttpFoundation\Response
     * @param $id
     * @Route("promotion/create/user", name="promotion_add_process_u")
     * @Method({"POST"})
     */
    public function addUserPromotionProccessActon(Request $request)

    {
        $Promotion = new Promotion();
        $form = $this->createForm(UserPromotionType::class, $Promotion)
            ->add("create", SubmitType::class, array(
                'attr' => array('class' => 'btn-success', 'formnovalidate' => true)))
            ->add("cancel", SubmitType::class, array(
                    'attr' => array('class' => 'btn-primary', 'formnovalidate' => true))
            );
        $form->handleRequest($request);
        if ($form->get('cancel')->isClicked()) {
            return $this->redirectToRoute('promotion_list_p');
        }

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($Promotion);
            $entityManager->flush();

            $this->addFlash("info", "Promotion with name " . $Promotion->getName() . " was added successfully");


            return $this->redirectToRoute('promotion_list_u');


        }


        return $this->render('@Shop/Promotion/create.html.twig',
            ['PromotionForm' => $form->createView()]);


    }


    /**
     *
     * @Route("promotion/edit/category/{id}", name="promotion_edit_c")
     * @Method({"GET"})
     *
     * @param Promotion $promotion
     * @return Response
     */

    public function editCategoryPromotionAction(Promotion $promotion)
    {


        $form = $this->createForm(CategoryPromotionType::class, $promotion)
            ->add("edit", SubmitType::class, array(
                'attr' => array('class' => 'btn-warning', 'formnovalidate' => true)))
            ->add("cancel", SubmitType::class, array(

src/ShopBundle/Resources/views/Promotion/categorylist.html.twig
{% extends "@Shop/base.html.twig" %}

{% block content %}

    {% for msg in app.session.flashBag.get('delete') %}
        <div class="alert alert-danger">
            <h1>{{ msg }}</h1>
        </div>
    {% endfor %}
    {% for msg in app.session.flashBag.get('error') %}
        <div class="alert alert-danger">
            <h1>{{ msg }}</h1>
        </div>
    {% endfor %}

    {% set objects = pagination %}

    {% set firstItem = objects|first|default %}



    <div class="countainer">
        <div class="row">
            <div class="col-md-2 col-md-offset-1">
                <div class="panel panel-primary">
                    {% if firstItem %}
                        <div class="panel-heading">{{ firstItem }}</div>

                        <ul>
                            <li class="btn btn"><a href="{{ path('promotion_add_c') }}">NEW</a></li>
                        </ul>
                        <ul>
                            <li class="btn btn"><a href="{{ path('manage_main') }}">Manger Menu</a></li>
                        </ul>
                    {% endif %}
                    <div class="panel-body"></div>
                    <div class="panel-footer"></div>
                </div>
            </div>
            {% block paginatorhead %}
                {{ objects.getTotalItemCount }}
            {% endblock %}
            <div class="col-md-8 col-md-offset-0">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            {% for head in  firstItem.headcategory %}
                                {% if not  head|is_array %}
                                    <th>{{ head }}</th>
                                {% endif %}
                                {% if head|is_array %}
                                    {% for key ,value in head %}
                                        <th>{{ key|capitalize }}</th>
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}
                        </tr>
                        </thead>
                        <tbody>


                        {% for object in  objects %}
                            <tr>
                                {% for head in  firstItem.headcategory %}
                                    {% if head|is_array %}
                                        {% for key ,value in head %}
                                            <td>  {{ attribute(attribute(object,'get'~key),'get'~value) }}</td>
                                        {% endfor %}
                                    {% endif %}
                                    {% if not  head|is_array %}
                                        <td>{{ attribute(object, 'get'~head) }}</td>
                                    {% endif %}

                                {% endfor %}

                                {% if firstItem %}

                                    <td>
                                        <a href="{{ path('promotion_edit_c',{'id' :attribute(object, 'getid') }) }}"
                                           class="btn btn-warning">Edit</a>
                                    </td>
                                    <td>
                                        <form method="post"
                                              action="{{ path('promotion_delete_c', {'id':attribute(object, 'getid')}) }}">
                                            <button type="submit" class="btn btn-danger confirm-delete">Delete</button>
                                        </form>
                                    </td>
                                {% endif %}

                            </tr>



                        {% endfor %}
                        </tbody>
                    </table>
                    {{ knp_pagination_render(objects) }}
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <a href="#" data-dismiss="modal" aria-hidden="true" class="close">×</a>
                    <h3>Delete</h3>
                </div>
                <div class="modal-body">
                    <p>You are about to delete.</p>
                    <p>Do you want to proceed?</p>
                </div>
                <a id="btnYes" class="btn danger">Yes</a>
                <a href="#" data-dismiss="modal" aria-hidden="true" class="btn secondary">No</a>
            </div>
        </div>

    </div>
{% endblock %}

src/ShopBundle/Resources/views/Promotion/create.html.twig
{% extends "@Shop/base.html.twig" %}


{% block content %}
    <div class="countainer-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                {{ form_start(promotionForm) }}
                {{ form_widget(promotionForm) }}
                {{ form_errors(promotionForm) }}
                {{ form_end(promotionForm) }}
            </div>
        </div>
    </div>

{% endblock %}

src/ShopBundle/Resources/views/Promotion/edit.html.twig
{% extends '@Shop/base.html.twig' %}

{% block content %}
    <div class="countainer-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                {{ form_start(editForm) }}
                {{ form_widget(editForm) }}
                {{ form_errors(editForm) }}
                {{ form_end(editForm) }}
            </div>
        </div>

    </div>

{% endblock %}

src/ShopBundle/Resources/views/Promotion/list.html.twig
{% extends "@Shop/base.html.twig" %}
{% import '@Shop/macro.html.twig' as rgrid %}

{% block content %}
    {{ rgrid.rendergrid(pagination) }}


{% endblock %}

src/ShopBundle/Resources/views/Promotion/productlist.html.twig
{% extends "@Shop/base.html.twig" %}

{% block content %}

    {% for msg in app.session.flashBag.get('delete') %}
        <div class="alert alert-danger">
            <h1>{{ msg }}</h1>
        </div>
    {% endfor %}
    {% for msg in app.session.flashBag.get('error') %}
        <div class="alert alert-danger">
            <h1>{{ msg }}</h1>
        </div>
    {% endfor %}

    {% set objects = pagination %}

    {% set firstItem = objects|first|default %}



    <div class="countainer">
        <div class="row">
            <div class="col-md-2 col-md-offset-1">
                <div class="panel panel-primary">
                    {% if firstItem %}
                        <div class="panel-heading">{{ firstItem }}</div>

                        <ul>
                            <li class="btn btn"><a href="{{ path('promotion_add_p') }}">NEW</a></li>
                        </ul>
                        <ul>
                            <li class="btn btn"><a href="{{ path('manage_main') }}">Manger Menu</a></li>
                        </ul>
                    {% endif %}
                    <div class="panel-body"></div>
                    <div class="panel-footer"></div>
                </div>
            </div>
            {% block paginatorhead %}
                {{ objects.getTotalItemCount }}
            {% endblock %}
            <div class="col-md-8 col-md-offset-0">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            {% for head in  firstItem.headproduct %}
                                {% if not  head|is_array %}
                                    <th>{{ head }}</th>
                                {% endif %}
                                {% if head|is_array %}
                                    {% for key ,value in head %}
                                        <th>{{ key|capitalize }}</th>
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}
                        </tr>
                        </thead>
                        <tbody>


                        {% for object in  objects %}
                            <tr>
                                {% for head in  firstItem.headproduct %}
                                    {% if head|is_array %}
                                        {% for key ,value in head %}
                                            <td>  {{ attribute(attribute(object,'get'~key),'get'~value) }}</td>
                                        {% endfor %}
                                    {% endif %}
                                    {% if not  head|is_array %}
                                        <td>{{ attribute(object, 'get'~head) }}</td>
                                    {% endif %}

                                {% endfor %}

                                {% if firstItem %}

                                    <td>
                                        <a href="{{ path('promotion_edit_p',{'id' :attribute(object, 'getid') }) }}"
                                           class="btn btn-warning">Edit</a>
                                    </td>
                                    <td>
                                        <form method="post"
                                              action="{{ path('promotion_delete_p', {'id':attribute(object, 'getid')}) }}">
                                            <button type="submit" class="btn btn-danger confirm-delete">Delete</button>
                                        </form>
                                    </td>
                                {% endif %}

                            </tr>



                        {% endfor %}
                        </tbody>
                    </table>
                    {{ knp_pagination_render(objects) }}
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <a href="#" data-dismiss="modal" aria-hidden="true" class="close">×</a>
                    <h3>Delete</h3>
                </div>
                <div class="modal-body">
                    <p>You are about to delete.</p>
                    <p>Do you want to proceed?</p>
                </div>
                <a id="btnYes" class="btn danger">Yes</a>
                <a href="#" data-dismiss="modal" aria-hidden="true" class="btn secondary">No</a>
            </div>
        </div>

    </div>
{% endblock %}

src/ShopBundle/Resources/views/Promotion/usercreate.html.twig
{% extends "@Shop/base.html.twig" %}


{% block content %}


    <div class="row">
    <div class="col-md-12 ">
        <div class="col-md-3 ">
            {{ form_start(promotionForm) }}
            {{ form_errors(promotionForm) }}
            {{ form_widget(promotionForm.children.promotion) }}
        </div>
        <div class="col-md-2 ">
            {{ form_label(promotionForm.children.item) }}
            {{ form_widget(promotionForm.children.item) }}
            {{ form_label(promotionForm.children.value1) }}
            {{  form_widget(promotionForm.children.value1) }}
            {{ form_label(promotionForm.children.rule) }}
            {{ form_widget(promotionForm.children.rule) }}
            {{ form_label(promotionForm.children.value2) }}
            {{ form_widget(promotionForm.children.value2) }}
            {{ form_label(promotionForm.children.logic) }}
            {{ form_widget(promotionForm.children.logic) }}
            {{ form_label(promotionForm.children.value3) }}
            {{ form_widget(promotionForm.children.value3) }}
            {{ form_label(promotionForm.children.rule2) }}
            {{ form_widget(promotionForm.children.rule2) }}
            {{ form_label(promotionForm.children.value4) }}
            {{ form_widget(promotionForm.children.value4) }}
            {{ form_rest(promotionForm) }}
            {{ form_end(promotionForm) }}
        </div>

    </div>


{% endblock %}